-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Mission configuration file for the Skynet-IADS framework
-- see https://github.com/walder/Skynet-IADS
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
--
-- RetLab additions over upstream's bridge (docs/dev/design/retlab-skynet-return-notes.md):
--  * DeadC2 -- a C2 node the campaign already knows is destroyed is registered as
--    a dead stand-in, so the SAMs behind it stay degraded on later turns.
--  * AWACS fold -- a ground-starting AWACS is added once it spawns, not skipped.
--  * Exclude SA-15 works -- upstream's inner `local sams` shadowed the list.
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Skynet-IADS plugin - configuration
env.info("DCSRetribution|Skynet-IADS plugin - configuration")

if dcsRetribution and SkynetIADS then

    -- specific options
    local createRedIADS = false
    local createBlueIADS = false
    local includeRedInRadio = false
    local includeBlueInRadio = false
    local debugRED = false
    local debugBLUE = false
    local actMobile = false    -- did not change to actMobile_shorad for backwards compatibility
    local actMobileMaxEmissionTime = 30
    local actMobileMinimumScootDistance = 300
    local actMobileMaximumScootDistance = 500
    local actMobile_exclude_SA15 = false
    local actMobile_merad = false
    local actMobileMaxEmissionTime_merad = 120
    local actMobileMinimumScootDistance_merad = 500
    local actMobileMaximumScootDistance_merad = 3000
    local adjustGoLiveRange = false
    local adjustGoLiveRange_SA5 = 100
    local adjustGoLiveRange_SA10 = 100
    local adjustGoLiveRange_SA17 = 100
    local adjustGoLiveRange_SA20 = 100
    local adjustGoLiveRange_SA23 = 100

    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.skynetiads then
            createRedIADS = dcsRetribution.plugins.skynetiads.createRedIADS
            createBlueIADS = dcsRetribution.plugins.skynetiads.createBlueIADS
            includeRedInRadio = dcsRetribution.plugins.skynetiads.includeRedInRadio
            includeBlueInRadio = dcsRetribution.plugins.skynetiads.includeBlueInRadio
            debugRED = dcsRetribution.plugins.skynetiads.debugRED
            debugBLUE = dcsRetribution.plugins.skynetiads.debugBLUE
            actMobile = dcsRetribution.plugins.skynetiads.actMobile
            actMobileMaxEmissionTime = dcsRetribution.plugins.skynetiads.actMobileMaxEmissionTime
            actMobileMinimumScootDistance = dcsRetribution.plugins.skynetiads.actMobileMinimumScootDistance
            actMobileMaximumScootDistance = dcsRetribution.plugins.skynetiads.actMobileMaximumScootDistance
            actMobile_exclude_SA15 = dcsRetribution.plugins.skynetiads.actMobile_exclude_SA15
            actMobile_merad = dcsRetribution.plugins.skynetiads.actMobile_merad
            actMobileMaxEmissionTime_merad = dcsRetribution.plugins.skynetiads.actMobileMaxEmissionTime_merad
            actMobileMinimumScootDistance_merad = dcsRetribution.plugins.skynetiads.actMobileMinimumScootDistance_merad
            actMobileMaximumScootDistance_merad = dcsRetribution.plugins.skynetiads.actMobileMaximumScootDistance_merad
            adjustGoLiveRange = dcsRetribution.plugins.skynetiads.adjustGoLiveRange
            adjustGoLiveRange_SA5 = dcsRetribution.plugins.skynetiads.adjustGoLiveRange_SA5
            adjustGoLiveRange_SA10 = dcsRetribution.plugins.skynetiads.adjustGoLiveRange_SA10
            adjustGoLiveRange_SA17 = dcsRetribution.plugins.skynetiads.adjustGoLiveRange_SA17
            adjustGoLiveRange_SA20 = dcsRetribution.plugins.skynetiads.adjustGoLiveRange_SA20
            adjustGoLiveRange_SA23 = dcsRetribution.plugins.skynetiads.adjustGoLiveRange_SA23
        end
    end

    env.info(string.format("DCSRetribution|Skynet-IADS plugin - createRedIADS=%s", tostring(createRedIADS)))
    env.info(string.format("DCSRetribution|Skynet-IADS plugin - createBlueIADS=%s", tostring(createBlueIADS)))
    env.info(string.format("DCSRetribution|Skynet-IADS plugin - includeRedInRadio=%s", tostring(includeRedInRadio)))
    env.info(string.format("DCSRetribution|Skynet-IADS plugin - includeBlueInRadio=%s", tostring(includeBlueInRadio)))
    env.info(string.format("DCSRetribution|Skynet-IADS plugin - debugRED=%s", tostring(debugRED)))
    env.info(string.format("DCSRetribution|Skynet-IADS plugin - debugBLUE=%s", tostring(debugBLUE)))

    -- A C2 node killed on an earlier turn may have no DCS object left to look up
    -- (destructible scenery never has one), and Skynet reads a SAM with no comms
    -- or power object as fully connected. The campaign names those nodes in
    -- DeadC2; this registers each as an object that answers isExist() == false,
    -- which is all Skynet asks of a node. A command centre is also asked its
    -- coalition and type.
    local function deadStandIn(name, coalitionID)
        return {
            isExist = function() return false end,
            getName = function() return name end,
            getTypeName = function() return "DeadC2" end,
            getCoalition = function() return coalitionID end,
            getPosition = function() return { p = { x = 0, y = 0, z = 0 } } end,
            getPoint = function() return { x = 0, y = 0, z = 0 } end,
        }
    end

    local function c2Object(name, deadC2, coalitionID)
        if deadC2[name] then
            env.info(string.format("DCSRetribution|Skynet-IADS plugin - %s is destroyed; registering a dead stand-in", name))
            return deadStandIn(name, coalitionID)
        end
        return StaticObject.getByName(name .. " object") -- pydcs adds ' object' to the unit name for static elements
    end

    local function deadC2Set(coalition_iads)
        local set = {}
        if coalition_iads and coalition_iads.DeadC2 then
            for _, name in pairs(coalition_iads.DeadC2) do
                set[name] = true
            end
        end
        return set
    end

    -- actual configuration code
    local function initializeIADSElement(iads, iads_unit, element, deadC2, coalitionID)
        if iads_unit == nil then
            -- skip processing of units which can not be handled by skynet
            return
        end
        if element.engagement_zone then
            iads_unit:setEngagementZone(element.engagement_zone)
        end
        if element.can_engage_harm then
            iads_unit:setCanEngageHARM(element.can_engage_harm)
        end
        if element.harm_detection_chance then
            iads_unit:setHARMDetectionChance(tonumber(element.harm_detection_chance))
        end
        if element.can_engage_air_weapon then
            iads_unit:setCanEngageAirWeapons(element.can_engage_air_weapon)
        end
        if element.go_live_range_in_percent then
            iads_unit:setGoLiveRangeInPercent(tonumber(element.go_live_range_in_percent))
        end
        if element.autonomous_behaviour then
            iads_unit:setAutonomousBehaviour(element.autonomous_behaviour)
        end
        if element.ConnectionNode then
            for i, cn in pairs(element.ConnectionNode) do
                env.info(string.format("DCSRetribution|Skynet-IADS plugin - adding IADS ConnectionNode %s", cn))
                local connection_node = c2Object(cn, deadC2, coalitionID)
                if connection_node then
                    iads_unit:addConnectionNode(connection_node)
                end
            end
        end
        if element.PowerSource then
            for i, ps in pairs(element.PowerSource) do
                env.info(string.format("DCSRetribution|Skynet-IADS plugin - adding IADS PowerSource %s", ps))
                local power_source = c2Object(ps, deadC2, coalitionID)
                if power_source then
                    iads_unit:addPowerSource(power_source)
                end
            end
        end
        if element.PD then
            for i, pd in pairs(element.PD) do
                env.info(string.format("DCSRetribution|Skynet-IADS plugin - adding IADS Point Defence %s", pd))
                local point_defence = iads:addSAMSite(pd)
                -- Skynet keeps the parent emitting under a HARM on its PDs' missile count alone,
                -- never asking whether a PD can hit a HARM, so a Strela-1 or gun PD holds an SA-11
                -- live into the shot (test 37). Pair only a PD Skynet rates HARM-capable; the rest
                -- still fight as ordinary SAM sites. retlab-skynet-return-notes.md.
                if point_defence ~= nil and point_defence:getCanEngageHARM() == true then
                    iads_unit:addPointDefence(point_defence)
                elseif point_defence ~= nil then
                    env.info(string.format("DCSRetribution|Skynet-IADS plugin - %s cannot engage a HARM; not paired as point defence", pd))
                end
            end
        end
    end

    local AWACS_RETRY_S = 60
    local AWACS_GIVE_UP_S = 5400

    local function initializeIADS(iads, coalition, inRadio, debug)

        local coalitionPrefix = "BLUE"
        if coalition == 1 then
            coalitionPrefix = "RED"
        end

        if debug then
            env.info("adding debug information")
            local iadsDebug = iads:getDebugSettings()
            iadsDebug.IADSStatus = true
            iadsDebug.samWentDark = true
            iadsDebug.contacts = true
            iadsDebug.radarWentLive = true
            iadsDebug.noWorkingCommmandCenter = true
            iadsDebug.ewRadarNoConnection = true
            iadsDebug.samNoConnection = true
            iadsDebug.jammerProbability = true
            iadsDebug.addedEWRadar = true
            iadsDebug.hasNoPower = true
            iadsDebug.harmDefence = true
            iadsDebug.samSiteStatusEnvOutput = true
            iadsDebug.earlyWarningRadarStatusEnvOutput = true
            iadsDebug.commandCenterStatusEnvOutput = true
        end

        -- add the AWACS. A ground-starting AWACS is not a spawned group yet, and
        -- it is often the coalition's only wide-area sensor, so keep looking for
        -- it: Skynet accepts a new EWR after activation. The coalition is read
        -- from the campaign's AWACs entry because the group may not exist yet.
        local pendingAwacs = {}
        if dcsRetribution.AWACs then
            local side = "blue"
            if coalition == 1 then
                side = "red"
            end
            for _, data in pairs(dcsRetribution.AWACs) do
                if data.coalition == nil or data.coalition == side then
                    table.insert(pendingAwacs, data.dcsGroupName)
                end
            end
        end
        local function addSpawnedAwacs()
            local remaining = {}
            for _, groupName in ipairs(pendingAwacs) do
                local group = Group.getByName(groupName)
                if group == nil then
                    table.insert(remaining, groupName)
                elseif group:getCoalition() == coalition then
                    local unit = group:getUnit(1)
                    if unit then
                        local unitName = unit:getName()
                        env.info(string.format("DCSRetribution|Skynet-IADS plugin - adding AWACS %s", unitName))
                        iads:addEarlyWarningRadar(unitName)
                    end
                end
            end
            pendingAwacs = remaining
            if #pendingAwacs > 0 and timer.getTime() < AWACS_GIVE_UP_S then
                return timer.getTime() + AWACS_RETRY_S
            end
            return nil
        end
        addSpawnedAwacs()
        if #pendingAwacs > 0 then
            env.info(string.format("DCSRetribution|Skynet-IADS plugin - %d AWACS not spawned yet; retrying every %d s", #pendingAwacs, AWACS_RETRY_S))
            timer.scheduleFunction(addSpawnedAwacs, nil, timer.getTime() + AWACS_RETRY_S)
        end

        -- add the IADS Elements: SAM, EWR, and Command Centers
        if dcsRetribution.IADS then
            local coalition_iads = dcsRetribution.IADS[coalitionPrefix]
            local deadC2 = deadC2Set(coalition_iads)
            if coalition_iads.Ewr then
                for _, unit in pairs(coalition_iads.Ewr) do
                    env.info(string.format("DCSRetribution|Skynet-IADS plugin - processing IADS EWR %s", unit.dcsGroupName))
                    local iads_unit = iads:addEarlyWarningRadar(unit.dcsGroupName)
                    initializeIADSElement(iads, iads_unit, unit, deadC2, coalition)
                end
            end
            if coalition_iads.Sam then
                for _, unit in pairs(coalition_iads.Sam) do
                    env.info(string.format("DCSRetribution|Skynet-IADS plugin - processing IADS SAM %s", unit.dcsGroupName))
                    local iads_unit = iads:addSAMSite(unit.dcsGroupName)
                    initializeIADSElement(iads, iads_unit, unit, deadC2, coalition)
                end
            end
            if coalition_iads.SamAsEwr then
                for _, unit in pairs(coalition_iads.SamAsEwr) do
                    env.info(string.format("DCSRetribution|Skynet-IADS plugin - processing IADS SAM as EWR %s", unit.dcsGroupName))
                    local iads_unit = iads:addSAMSite(unit.dcsGroupName)
                    if iads_unit ~= nil then
                        -- only process if its a valid skynet group
                        iads_unit:setActAsEW(true)
                        initializeIADSElement(iads, iads_unit, unit, deadC2, coalition)
                    end
                end
            end
            if coalition_iads.CommandCenter then
                for _, unit in pairs(coalition_iads.CommandCenter) do
                    env.info(string.format("DCSRetribution|Skynet-IADS plugin - processing IADS Command Center %s", unit.dcsGroupName))
                    local commandCenter = c2Object(unit.dcsGroupName, deadC2, coalition)
                    if commandCenter then
                        local iads_unit = iads:addCommandCenter(commandCenter)
                        initializeIADSElement(iads, iads_unit, unit, deadC2, coalition)
                    end
                end
            end
        end

        if inRadio then
            --activate the radio menu to toggle IADS Status output
            env.info("DCSRetribution|Skynet-IADS plugin - adding in radio menu")
            iads:addRadioMenu()
        end

        --activate the IADS
        iads:activate()
    end

    local function initializeMobileSams_shorad(iads)
        local sams = {"SA-8", "SA-9", "SA-13", "SA-15", "SA-19"}
        if actMobile_exclude_SA15 then
            sams = {"SA-8", "SA-9", "SA-13", "SA-19"}
        end
        for _, sam in ipairs(sams) do
            iads:getSAMSitesByNatoName(sam):setActMobile(true,actMobileMaxEmissionTime,actMobileMinimumScootDistance,actMobileMaximumScootDistance,nil)    --ActMobile SHORAD
        end
    end

    local function initializeMobileSams_merad(iads)
        local sams = {"SA-6", "SA-11", "SA-17"}
        for _, sam in ipairs(sams) do
            iads:getSAMSitesByNatoName(sam):setActMobile(true,actMobileMaxEmissionTime_merad,actMobileMinimumScootDistance_merad,actMobileMaximumScootDistance_merad,nil)    --ActMobile MERAD
        end
    end

    local function setGoLiveRange(iads)
        iads:getSAMSitesByNatoName('SA-5'):setGoLiveRangeInPercent(adjustGoLiveRange_SA5)
        iads:getSAMSitesByNatoName('SA-10'):setGoLiveRangeInPercent(adjustGoLiveRange_SA10)
        iads:getSAMSitesByNatoName('SA-17'):setGoLiveRangeInPercent(adjustGoLiveRange_SA17)
        iads:getSAMSitesByNatoName('SA-20'):setGoLiveRangeInPercent(adjustGoLiveRange_SA20)
        iads:getSAMSitesByNatoName('SA-23'):setGoLiveRangeInPercent(adjustGoLiveRange_SA23)
    end


    ------------------------------------------------------------------------------------------------------------------------------------------------------------
    -- create the IADS networks
    -------------------------------------------------------------------------------------------------------------------------------------------------------------
    if createRedIADS then
        env.info("DCSRetribution|Skynet-IADS plugin - creating red IADS")
        local redIADS = SkynetIADS:create("IADS")
        initializeIADS(redIADS, 1, includeRedInRadio, debugRED) -- RED
        if actMobile then
            initializeMobileSams_shorad(redIADS)
        end
        if actMobile_merad then
            initializeMobileSams_merad(redIADS)
        end
        if adjustGoLiveRange then
            setGoLiveRange(redIADS)
        end
    end

    if createBlueIADS then
        env.info("DCSRetribution|Skynet-IADS plugin - creating blue IADS")
        local blueIADS = SkynetIADS:create("IADS")
        initializeIADS(blueIADS, 2, includeBlueInRadio, debugBLUE) -- BLUE
        if actMobile then
            initializeMobileSams_shorad(blueIADS)
        end
        if actMobile_merad then
            initializeMobileSams_merad(blueIADS)
        end
        if adjustGoLiveRange then
            setGoLiveRange(blueIADS)
        end
    end

end
