"""Campaign management: pilots, squadrons, HQ and planner automation."""

from dataclasses import dataclass
from typing import TYPE_CHECKING


from ..booleanoption import boolean_option
from ..boundedintoption import bounded_int_option
from ..choicesoption import choices_option
from ..textoption import text_option
from ...ground_forces.combat_stance import CombatStance

if TYPE_CHECKING:
    pass
from ..enums import AutoAtoBehavior, CloudPresetPack
from ..layout import (
    CAMPAIGN_MANAGEMENT_PAGE,
    FLIGHT_PLANNER_AUTOMATION,
    GENERAL_SECTION,
    HQ_AUTOMATION_SECTION,
    PILOTS_AND_SQUADRONS_SECTION,
)


@dataclass
class CampaignManagementSettings:
    # Campaign management
    # General
    squadron_random_chance: int = bounded_int_option(
        "Generated-squadron aircraft randomization (%)",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=50,
        min=0,
        max=100,
        detail=(
            "Aircraft type selection is governed by the campaign and the squadron definitions available to "
            "Retribution. Squadrons are generated by Retribution if the faction does not have access to the campaign "
            "designer's squadron/aircraft definitions. Raise this to increase aircraft variety: some "
            "selections are then made at random instead of from the priority list."
        ),
    )
    restrict_weapons_by_date: bool = boolean_option(
        "Restrict weapons by campaign date (incomplete data)",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "Restricts weapon availability based on the campaign date. Data is "
            "extremely incomplete so does not affect all weapons."
        ),
    )
    restrict_props_by_date: bool = boolean_option(
        "Restrict aircraft options by date (WIP)",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "Restricts era-defining aircraft mission options (e.g. the JHMCS helmet "
            "cueing selection) based on the campaign date: gated options are hidden "
            "from the payload editor and clamped to a period-correct value at "
            "mission generation. Independent of the weapons restriction so either "
            "can be enforced alone. Data is curated per airframe and incomplete."
        ),
    )
    alternate_victory_domination: int = bounded_int_option(
        "Domination victory (% of bases held)",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section="Victory conditions",
        default=0,
        min=0,
        max=100,
        detail=(
            "0 disables (the default). Otherwise, holding at least this percentage "
            "of the map's non-neutral bases wins the campaign at the turn boundary "
            "-- a limited war ends when the objective area is held, without the "
            "total conquest the stock ending demands. Adds to the normal endings, "
            "never replaces them. Pick a threshold above your starting share or "
            "the campaign ends immediately -- the VICTORY chip on the map ribbon "
            "shows the live percentage. Works on any campaign; a campaign's own "
            "victory conditions stack with it."
        ),
    )
    alternate_victory_attrition: int = bounded_int_option(
        "Attrition victory (enemy air below % of start)",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section="Victory conditions",
        default=0,
        min=0,
        max=90,
        detail=(
            "0 disables (the default). Otherwise, grinding the enemy's total owned "
            "airframes below this percentage of their campaign-start strength wins "
            "the campaign -- destroy the enemy's military potential instead of "
            "capturing every base. Measured against the force at campaign start "
            "(enemy procurement rebuying airframes counts against you, so the "
            "fight stays honest); the VICTORY chip on the map ribbon shows the "
            "live percentage. Adds to the normal endings, never replaces them."
        ),
    )
    coin_insurgency: bool = boolean_option(
        "COIN insurgent replenishment",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "The enemy fights as an insurgency: its strongholds freely regenerate a "
            "small trickle of irregular units each turn (infantry, technicals, AAA "
            "-- never armor or SAMs), refilling toward their campaign-start garrison "
            "but never growing. The rate is throttled by each stronghold's ammo "
            "caches -- find and destroy them to collapse the trickle to a residual "
            "floor. Body count alone cannot win; caches, the supply trail, and "
            "patience decide. Intended for COIN campaigns that preseed it on."
        ),
    )
    coin_reinfiltration: bool = boolean_option(
        "COIN re-infiltration (insurgency retakes ground)",
        enabled_when="coin_insurgency",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "The insurgency can retake ground you cleared but did not hold. Over "
            "several turns an under-garrisoned base near a healthy stronghold draws "
            "a staged, announced infiltration -- a cell appears, then a supply cache, "
            "then the base changes hands -- each stage a real unit on the map you can "
            "strike to stop it. Garrison it, kill the cell or cache, or strangle the "
            "source stronghold's caches to break the attempt. Total insurgent bases "
            "never exceed the campaign start (relocate, never grow); a completed flip "
            "costs you the base like any other capture. Requires COIN replenishment "
            "on; intended for COIN campaigns that preseed it."
        ),
    )
    coin_ied: bool = boolean_option(
        "COIN roadside IEDs (sweep the trail)",
        enabled_when="coin_insurgency",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "The insurgent supply roads are mined. Hidden emplacements appear on the "
            "ratline -- an emplaced device guarded by a small security team, or a "
            "mobile VBIED driving for your lines -- each shown only as a search "
            "circle on its road until you engage it. Find and strike them (CAS/Armed "
            "Recon) within a few turns. Destroying the device clears the bomb "
            "(killing the team alone does not); one you leave un-swept detonates on "
            "the coalition and the casualties are announced. Requires COIN "
            "replenishment on; intended for COIN campaigns that preseed it."
        ),
    )
    coin_hvt: bool = boolean_option(
        "COIN high-value targets (hunt the leadership)",
        enabled_when="coin_insurgency",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "The war is a manhunt. A named insurgent leader periodically surfaces near "
            "a stronghold for a limited strike window -- a real convoy, shown only as "
            "a search circle until you engage it. Kill it inside the window or it "
            "escapes; either way the outcome is announced. Requires COIN replenishment "
            "on; intended for COIN campaigns that preseed it."
        ),
    )
    coin_dispersed_cells: bool = boolean_option(
        "COIN dispersed cells (patrol the countryside)",
        enabled_when="coin_insurgency",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "The insurgency operates between the strongholds, not just in them. Small "
            "cells appear out in the open countryside, each shown only as a search "
            "circle until you engage it -- patrol for them (CAS/Armed Recon), don't "
            "just hit known positions. A cell you leave alone "
            "matures and slips into its home stronghold, bringing a destroyed ammo cache "
            "back into operation (re-opening the regeneration you worked to shut off), "
            "or reinforcing its garrison. Hunting the field cells is how you keep a "
            "stronghold starved. Requires COIN replenishment on; intended for COIN "
            "campaigns that preseed it."
        ),
    )
    coin_harassment: bool = boolean_option(
        "COIN indirect fire on forward bases (the FOB war)",
        enabled_when="coin_insurgency",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "The rear is not a safe area. Friendly airfields, FARPs and FOBs within "
            "mortar reach of an insurgent stronghold draw sporadic rocket/mortar "
            "harassment fire during the mission -- mostly noise and smoke with a "
            "modest bite, pressure rather than precision. Pushing the strongholds "
            "back (or clearing them) is what silences the fire. Never targets a "
            "field a player spawns at or recovers to this mission, and a startup "
            "grace period holds all fire while flights align. Requires COIN "
            "replenishment on; intended for COIN campaigns that preseed it."
        ),
    )
    long_range_carrier_ops: bool = boolean_option(
        "Long-range carrier strike package",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "For campaigns whose carrier stands off far beyond the auto-planner's "
            "reach (e.g. the Arabian-Sea cycle ~800 km from Afghanistan): frag one "
            "deterministic carrier strike package each turn from the boat's own "
            "squadrons -- a Hornet section on the nearest legal target, an A-6 tanker "
            "escorting the route (ingress/egress), and an E-2 on AEWC -- which the "
            "stock range-gated planner would otherwise leave on the deck. Also raise "
            "'Auto-planner maximum mission range for airplanes' so the carrier air is "
            "assignable to the wider war. Intended for campaigns that preseed it on."
        ),
    )
    motorpool_enabled: bool = boolean_option(
        "Spawn strikeable motorpool reserves",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=True,
        detail=(
            "Render each control point's not-yet-deployed reserve armor as a "
            "strikeable motorpool (only where the campaign authored one). "
            "Destroying reserves forces the owner to repurchase."
        ),
    )
    motorpool_spawn_cap: int = bounded_int_option(
        "Maximum motorpool vehicles per turn",
        enabled_when="motorpool_enabled",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=10,
        min=0,
        max=25,
        detail=(
            "Caps how many reserve vehicles a control point renders across its "
            "motorpool(s) per turn. Lower this if motorpools hurt mission "
            "performance."
        ),
    )
    apply_target_overrides_to_loadouts: bool = boolean_option(
        "Apply target-based weapon settings to player loadouts",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=True,
        detail=(
            "When enabled, applies target-specific weapon settings from weapon "
            "configurations to player-controlled aircraft. AI aircraft always receive "
            "target-based settings. This includes settings for degraded loadouts."
        ),
    )
    cloud_preset_pack: CloudPresetPack = choices_option(
        "Custom cloud preset pack",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=CloudPresetPack.NONE,
        choices={v.value: v for v in CloudPresetPack},
        detail=(
            "Make a community cloud-preset weather mod's presets available to the "
            "mission generator. Pick the pack you have installed in DCS. Only one can "
            "be active at a time, since the packs reuse the same preset keys for "
            "different clouds. 'None' uses the stock DCS presets."
        ),
    )
    atmosx_live_weather: bool = boolean_option(
        "Use ATMOS-X live weather",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default=False,
        detail=(
            "Replace the generated weather with a real METAR observation, fetched by "
            "the ATMOS-X CLI for a station on this terrain. The mission keeps its own "
            "date and time and takes only the sky. If the observation cannot be "
            "fetched -- no ATMOS-X, no network, nothing reported for that station -- "
            "the turn keeps the weather Retribution generated and says so in the log."
        ),
        enabled_when=("cloud_preset_pack", CloudPresetPack.ATMOSX),
    )
    atmosx_cli_path: str = text_option(
        "ATMOS-X CLI path",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default="",
        placeholder="Detected automatically",
        detail=(
            "Full path to atmosx-cli.exe. Leave blank to find it from the ATMOS-X "
            "installation registered with Windows; set it only if ATMOS-X was not "
            "installed by its installer or lives somewhere unusual."
        ),
        enabled_when=("cloud_preset_pack", CloudPresetPack.ATMOSX),
        advanced=True,
    )
    atmosx_metar_station: str = text_option(
        "ATMOS-X METAR station (ICAO)",
        page=CAMPAIGN_MANAGEMENT_PAGE,
        section=GENERAL_SECTION,
        default="",
        placeholder="Nearest to your base",
        detail=(
            "Which station to read the weather from, e.g. LCLK. Leave blank and the "
            "station is chosen from the airfields ATMOS-X knows on this terrain: the "
            "one you are flying from if it reports, otherwise the closest that does."
        ),
        enabled_when=("cloud_preset_pack", CloudPresetPack.ATMOSX),
        advanced=True,
    )
    # Pilots and Squadrons
    ai_pilot_levelling: bool = boolean_option(
        "Allow AI pilot leveling",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=True,
        detail=(
            "Set whether or not AI pilots will level up after completing a number of"
            " sorties. Since pilot level affects the AI skill, you may wish to disable"
            " this, lest you face an Ace!"
        ),
    )
    #: Feature flag for squadron limits.
    enable_squadron_pilot_limits: bool = boolean_option(
        "Enable per-squadron pilot limits",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=True,
        detail=(
            "If set, squadrons will be limited to a maximum number of pilots and dead "
            "pilots will replenish at a fixed rate, set by 'Maximum number of pilots per "
            "squadron' and 'Squadron pilot replenishment rate'. Auto-purchase may buy "
            "aircraft for which there are no pilots available, so this feature is "
            "still a work-in-progress."
        ),
    )
    #: The maximum number of pilots a squadron can have at one time. Changing this after
    #: the campaign has started will have no immediate effect; pilots already in the
    #: squadron will not be removed if the limit is lowered and pilots will not be
    #: immediately created if the limit is raised.
    squadron_pilot_limit: int = bounded_int_option(
        "Maximum number of pilots per squadron",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        enabled_when="enable_squadron_pilot_limits",
        default=16,
        min=6,
        max=72,
        detail=(
            "Sets the maximum number of pilots a squadron may have active. "
            "Changing this value will not have an immediate effect, but will alter "
            "replenishment for future turns."
        ),
    )
    #: The number of pilots a squadron can replace per turn.
    squadron_replenishment_rate: int = bounded_int_option(
        "Squadron pilot replenishment rate",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        enabled_when="enable_squadron_pilot_limits",
        default=4,
        min=1,
        max=20,
        detail=(
            "Sets the maximum number of pilots that will be recruited to each squadron "
            "at the end of each turn. Squadrons will not recruit new pilots beyond the "
            "pilot limit, but each squadron with room for more pilots will recruit "
            "this many pilots each turn up to the limit."
        ),
    )
    # Feature flag for squadron limits.
    enable_squadron_aircraft_limits: bool = boolean_option(
        "Enable per-squadron aircraft limits",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=False,
        detail=(
            "If set, squadrons will not be able to buy more aircraft than the configured maximum."
        ),
    )
    # Combat Search and Rescue
    csar_enabled: bool = boolean_option(
        "Enable CSAR for the player coalition",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=True,
        detail="Enable CSAR rescue flights for OWNFOR (BLUE) Coalition.",
    )
    csar_enabled_red: bool = boolean_option(
        "Enable CSAR for the enemy coalition",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=True,
        detail="Enable CSAR rescue flights for OPFOR (RED) Coalition.",
    )
    csar_ejection_chance: int = bounded_int_option(
        "CSAR pilot survival chance (%)",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=40,
        min=0,
        max=100,
        detail=(
            "Chance of pilot survival and becoming a downed pilot for aircraft losses "
            "where DCS did not report an ejection (AI kills and all losses on skipped/simulated turns). "
            "Real in-mission ejections always produce a downed pilot."
        ),
    )
    csar_control_point_radius: int = bounded_int_option(
        "Control point radius resolving a downed pilot (NM)",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=15,
        min=0,
        max=100,
        detail=(
            "A pilot who comes down this close to a control point does not need a "
            "rescue flight: inside a friendly one they make their own way back and "
            "go straight into recovery, inside an enemy one they are captured and "
            "go missing in action. Only pilots outside every control point's radius "
            "become downed pilots on the map. Set to 0 to always require a rescue."
        ),
    )
    csar_cluster_radius: int = bounded_int_option(
        "Collect downed pilots within (m) on one flight",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=1000,
        min=0,
        max=5000,
        detail=(
            "Downed pilots this close together are collected by a single AI rescue "
            "flight rather than one flight each: the survivors walk to the same "
            "landing zone, or are hoisted on the same hover. Only affects the "
            "auto-planner -- a package planned by hand still targets one pilot. Set "
            "to 0 to plan a separate flight for every pilot."
        ),
    )
    csar_survival_turns: int = bounded_int_option(
        "Turns a downed pilot survives",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=3,
        min=1,
        max=10,
        detail=(
            "Number of turns a downed pilot in friendly rear territory waits for "
            "rescue before going missing in action."
        ),
    )
    csar_survival_turns_hostile: int = bounded_int_option(
        "Turns a downed pilot survives near the front",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=2,
        min=1,
        max=10,
        detail=(
            "Number of turns a downed pilot in hostile territory or close to a front "
            "line, where enemy ground forces are more likely to capture them, waits for "
            "rescue before going missing in action."
        ),
    )
    csar_ai_recovery_turns: int = bounded_int_option(
        "Turns a rescued AI pilot recovers",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=2,
        min=0,
        max=10,
        detail=(
            "Number of turns a rescued AI pilot is unavailable (recovering) before "
            "returning to active duty."
        ),
    )
    csar_player_recovery_turns: int = bounded_int_option(
        "Turns a rescued player pilot recovers",
        CAMPAIGN_MANAGEMENT_PAGE,
        PILOTS_AND_SQUADRONS_SECTION,
        default=1,
        min=0,
        max=10,
        detail=(
            "Number of turns a rescued human pilot is unavailable (recovering) before "
            "returning to active duty."
        ),
    )
    # Campaign phases (W3; the design notes went with §40, features doc §40). Tier-0
    # inference is the DECIDED default for every campaign; this is the kill switch.
    continuous_campaign_clock: bool = boolean_option(
        "Continuous time & weather",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign clock & weather",
        detail=(
            "Make the campaign flow as one continuous timeline. The mission "
            "clock marches forward a few hours each turn (a sortie plus "
            "turnaround) and the date rolls over at midnight, instead of "
            "teleporting between disjoint dawn/day/dusk/night bands. Weather "
            "evolves from the previous turn -- fronts roll in and clear over "
            "several turns -- instead of an independent random draw each turn. "
            "Requires day-and-night missions (the day-only / night-only mission "
            "time settings opt out of the natural cycle and fall back to the "
            "per-turn rotation). Turn off for the stock per-turn behavior."
        ),
        # Stock default (2026-08-09 re-convergence): upstream rotates time of
        # day per turn with memoryless weather. RetLab planner suite preset
        # turns this on.
        default=False,
    )
    # HQ Automation
    automate_runway_repair: bool = boolean_option(
        "Automate runway repairs",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=False,
    )
    automate_front_line_reinforcements: bool = boolean_option(
        "Automate front-line purchases",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=False,
    )
    automate_aircraft_reinforcements: bool = boolean_option(
        "Automate aircraft purchases",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=False,
    )
    auto_ato_behavior: AutoAtoBehavior = choices_option(
        "Automatic package planning behavior",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=AutoAtoBehavior.Default,
        choices={v.value: v for v in AutoAtoBehavior},
        detail=(
            "Aircraft auto-purchase is directed by the auto-planner, so disabling "
            "auto-planning disables auto-purchase."
        ),
    )
    auto_ato_behavior_awacs: bool = boolean_option(
        "Automatic AWACS package planning",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=True,
    )
    auto_ato_behavior_tankers: bool = boolean_option(
        "Automatic theater-tanker package planning",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=False,
    )
    auto_ato_player_missions_asap: bool = boolean_option(
        "Automatically generated packages with players are scheduled ASAP",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=True,
    )
    # §109. Was Game.opfor_ai_enabled (a Developer tools toggle) until 2026-10-10.
    outside_ai_plans_red: bool = boolean_option(
        "Outside AI plans red",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=False,
        detail=(
            "Lets the AI on your AI connect link (Developer tools > Copy AI connect "
            "link) change red's missions and purchases. The game's own planner still "
            "plans and buys for red at the start of every turn; the AI keeps that "
            "plan, changes it or clears it. If red has no packages at Take Off, the "
            "game's planner plans red's missions again. Off, the AI can only read "
            "red's turn and report."
        ),
    )
    sp_pilot_mode: bool = boolean_option(
        "SP Pilot Mode (fly the next turn without planning it)",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=False,
        detail=(
            "For single-player: after accepting mission results, offer to fly the "
            "next turn straight away instead of returning to the map to plan it. "
            "You pick an AIRCRAFT first -- any type your wing can put up, not just "
            "the ones the commander happened to frag -- and then a sortie in that "
            "jet, taking ONE seat with AI wingmen exactly as in multiplayer. The "
            "role comes from the air war (escort, strike, jamming -- whatever the "
            "package needs), so the aircraft is your variety choice and the job is "
            "the war's. Also shows a pre-turn briefing of the reasons this turn "
            "matters: aviators evading with their capture odds, enemy command "
            "damage you caused, and victory progress. "
            "The normal map/ATO planning path is untouched -- this is an express "
            "lane, not a replacement."
        ),
    )
    pilot_career_logbook: bool = boolean_option(
        "Pilot career logbook",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=True,
        detail=(
            "Keeps a permanent record for every pilot in the campaign: sorties, "
            "combat sorties, hours airborne, air/ground/naval kills, ejections "
            "and rank. Open it from the squadron dialog. The numbers come "
            "from what the mission actually recorded, so a jet that never left "
            "the ramp logs nothing and a kill is credited only when DCS names "
            "the killer. A record, not a reward -- nothing here unlocks an "
            "aircraft, changes availability or gates a mission. Turn it off and "
            "careers stop accumulating; what a pilot has already logged is kept."
        ),
    )
    lifetime_pilot_profiles: bool = boolean_option(
        "Lifetime pilot profiles (across every campaign)",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=True,
        detail=(
            "Keeps your own flying on record across every campaign, not just "
            "this one. Each pilot is identified by their DCS player name, so it "
            "needs no setup and a multiplayer host records every pilot who "
            "flew, each to their own profile. Open it from the Pilot Logbook "
            "button on the toolbar -- it works with no campaign loaded. Records "
            "lifetime sorties, hours, kills by type, a breakdown per aircraft, "
            "and the individual flights. Stored in a file beside your other "
            "Retribution settings, NOT in the save game, which is what lets it "
            "outlive a campaign. Turn it off and nothing is written; what is "
            "already recorded is kept."
        ),
    )
    supply_gated_reinforcement: bool = boolean_option(
        "Reinforcement follows the supply lines",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=True,
        detail=(
            "Your bases only rebuild their ground strength if supply can still "
            "reach them. A base with a road or sea route back to a rear area "
            "recovers in full. A base that can only be reached by air recovers "
            "at a quarter rate. A base the enemy has cut off entirely recovers "
            "nothing until the route is reopened. With this off, every base "
            "recovers the same amount every turn regardless of the situation."
        ),
    )
    assault_costs_the_attacker: bool = boolean_option(
        "Attacking costs more than defending",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=True,
        detail=(
            "Winning a front-line battle while on the offensive costs you part "
            "of the ground you just took -- the assault is paid for. Winning "
            "while dug in costs nothing. The losing side gives up the same "
            "amount either way. Fronts hold until they are pushed and give when "
            "they break, instead of sliding back and forth for free. With this "
            "off, the winner gains exactly what the loser loses."
        ),
    )
    scale_aware_front_line: bool = boolean_option(
        "Front line position counts the forces present",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=True,
        detail=(
            "Where the front line sits accounts for how much armor each side "
            "actually has there, not just how well each side is holding up. "
            "Two bases both at full strength no longer meet in the middle when "
            "one of them is far better equipped. With this off, only the "
            "abstract strength figure decides, and a base with five vehicles "
            "counts the same as one with five hundred."
        ),
    )
    terrain_weighted_front_line: bool = boolean_option(
        "Terrain slows the front line down",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=True,
        detail=(
            "Ground is harder to take where the going is bad. Pushing the front "
            "through terrain your vehicles cannot drive over costs several "
            "times the advantage that the same distance of open country costs, "
            "so fronts stall at passes and river crossings and run in the open. "
            "With this off the front slides at the same rate everywhere, "
            "regardless of what it is crossing."
        ),
    )
    front_line_salients: bool = boolean_option(
        "Front lines bulge instead of running straight",
        CAMPAIGN_MANAGEMENT_PAGE,
        "Campaign features",
        default=True,
        detail=(
            "The front is a bowed line rather than a straight one. Sectors "
            "facing open ground sit further forward than sectors backed against "
            "terrain vehicles cannot cross, so the line shows salients where "
            "the going is good. Ground forces are placed along the bulge and "
            "the F10 map draws it. The two ends still anchor between their "
            "control points, and the front as a whole does not move."
        ),
    )
    automate_front_line_stance: bool = boolean_option(
        "Automatically manage front line stances",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=True,
    )
    default_front_line_stance: CombatStance = choices_option(
        "Default front line stance",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        enabled_when=("automate_front_line_stance", False),
        # RETREAT is intentionally omitted -- never a sensible standing default.
        choices={
            "Aggressive": CombatStance.AGGRESSIVE,
            "Defensive": CombatStance.DEFENSIVE,
            "Ambush": CombatStance.AMBUSH,
            "Elimination": CombatStance.ELIMINATION,
            "Breakthrough": CombatStance.BREAKTHROUGH,
        },
        default=CombatStance.AGGRESSIVE,
        detail=(
            "Starting stance for your front lines at campaign start and after a "
            "capture. Only applies when 'Automatically manage front line stances' "
            "is off; otherwise the AI commander chooses the stance."
        ),
    )
    auto_procurement_balance: int = bounded_int_option(
        "AI ground unit procurement budget ratio (%) for OWNFOR",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        min=0,
        max=100,
        default=50,
        detail=(
            "Ratio (larger number -> more budget for ground units) "
            "that indicates how the AI procurement planner should "
            "spend its budget."
        ),
    )
    frontline_reserves_factor: int = bounded_int_option(
        "AI ground unit front-line reserves factor (%) for OWNFOR",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        min=0,
        max=1000,
        default=130,
        detail=(
            "Factor to be multiplied with the control point's unit count limit "
            "to calculate the procurement target for reserve troops at front-lines."
        ),
    )
    reserves_procurement_target: int = bounded_int_option(
        "AI ground unit reserves procurement target for OWNFOR",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        min=0,
        max=1000,
        default=10,
        detail=(
            "The number of units that will be bought as reserves for applicable control points."
        ),
    )
    auto_procurement_balance_red: int = bounded_int_option(
        "AI ground unit procurement budget ratio (%) for OPFOR",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        min=0,
        max=100,
        default=50,
        detail=(
            "Ratio (larger number -> more budget for ground units) "
            "that indicates how the AI procurement planner should "
            "spend its budget."
        ),
    )
    frontline_reserves_factor_red: int = bounded_int_option(
        "AI ground unit front-line reserves factor (%) for OPFOR",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        min=0,
        max=1000,
        default=130,
        detail=(
            "Factor to be multiplied with the control point's unit count limit "
            "to calculate the procurement target for reserve troops at front-lines."
        ),
    )
    reserves_procurement_target_red: int = bounded_int_option(
        "AI ground unit reserves procurement target for OPFOR",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        min=0,
        max=1000,
        default=10,
        detail=(
            "The number of units that will be bought as reserves for applicable control points."
        ),
    )
    adaptive_procurement: bool = boolean_option(
        "Price-weighted AI ground purchases",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        # Stock default (2026-08-09 re-convergence): upstream buys uniformly at
        # random. RetLab planner suite preset turns this on.
        default=False,
        detail=(
            "Each side's AI commander weights its ground-unit buys by price, the "
            "capability proxy the model has, so it fields its better hardware more "
            "often than its cheapest. A weighting, not a maximum: variety is kept. "
            "With this off, each buy is a uniform random pick among the units it "
            "can afford."
        ),
    )
    auto_repair_air_defenses: bool = boolean_option(
        "AI repairs SAM & EWR sites",
        CAMPAIGN_MANAGEMENT_PAGE,
        HQ_AUTOMATION_SECTION,
        default=False,
        detail=(
            "Each side's AI commander spends budget repairing a couple of "
            "destroyed SAM/EWR units per turn at surviving sites (full unit "
            "price -- the same repair the base card offers you), degraded sites "
            "and radars first. The enemy air-defense belt regenerates unless you "
            "keep pressure on it, so a rolled-back IADS stops being a one-way "
            "ratchet. Command centers and comms nodes are never repaired -- "
            "decapitation stays permanent. For your own side this only runs "
            "when runway repairs are automated."
        ),
    )
    # Flight Planner Automation
    #: The weight used for 2-ships.
    fpa_2ship_weight: int = bounded_int_option(
        "2-ship weight factor (WF2)",
        CAMPAIGN_MANAGEMENT_PAGE,
        FLIGHT_PLANNER_AUTOMATION,
        default=50,
        min=0,
        max=100,
        detail=(
            "Used as a distribution to randomize 2/3/4-ships for BARCAP, CAS, OCA and anti-ship flights. "
            "The weight W_i is calculated according to the following formula:<br />"
            "W_i = WF_i / (WF2 + WF3 + WF4)"
        ),
    )
    #: The weight used for 3-ships.
    fpa_3ship_weight: int = bounded_int_option(
        "3-ship weight factor (WF3)",
        CAMPAIGN_MANAGEMENT_PAGE,
        FLIGHT_PLANNER_AUTOMATION,
        default=35,
        min=0,
        max=100,
        detail="Relative weight used with WF2 and WF4; see the 2-ship setting.",
    )
    fpa_4ship_weight: int = bounded_int_option(
        "4-ship weight factor (WF4)",
        CAMPAIGN_MANAGEMENT_PAGE,
        FLIGHT_PLANNER_AUTOMATION,
        default=15,
        min=0,
        max=100,
        detail="Relative weight used with WF2 and WF3; see the 2-ship setting.",
    )
    primary_task_distance_factor: int = bounded_int_option(
        "Primary task distance weight (NM)",
        CAMPAIGN_MANAGEMENT_PAGE,
        FLIGHT_PLANNER_AUTOMATION,
        default=75,
        min=10,
        max=250,
        detail="A larger number will force the auto-planner to stick with squadrons that have a matching primary task."
        " A smaller number will ignore squadrons with a matching primary task that are too far out.",
    )
    csar_single_flight: bool = boolean_option(
        "Enable single flight CSAR",
        CAMPAIGN_MANAGEMENT_PAGE,
        FLIGHT_PLANNER_AUTOMATION,
        default=False,
        detail=(
            "Plans rescue packages with one helicopter instead of a pair. Cheaper "
            "in airframes and pilots, at the cost of having no wingman to cover the "
            "pickup or take over if the lead is lost. The 2/3/4-ship weight factors "
            "do not apply to CSAR either way."
        ),
    )
